#aircraft * sorties * weapon_count = stock to carry

sorties = {'Tanker':        1,
           'Recon':         1,
           'AEW':           1,
           'ASW':           5,
           'Attack':        3,
           'Bomber':        1.5,
           'CAS':           4,
           'EW':            2,
           'Fighter':       4,
           'Fighter Multi': 4,
           'Strike Fighter':4}
cm =  {'AEW':           1,
       'ASuW':          1,
       'ASW':           5,
       'Attack':        4,
       'CAS':           4,
       'Fighter':       5,
       'Fighter Multi': 5,
       'Strike Fighter':4}
buoy ={'ASuW':          3,
       'ASW':           5}
tank ={'Cargo':         0,
       'Tanker':        2,}
nuke_bomb ={'Attack':        0.17,
            'Bomber':        0.34,
            'Fighter':       0.17,
            'Fighter Multi': 0.17,
            'Strike Fighter':0.17}
rockets = {'ASuW':          2,
           'ASW':           2,
           'Attack':        7,
           'Bomber':        3,
           'CAS':           5,
           'Fighter Multi': 4,
           'Strike Fighter':5}
gun  ={'Cargo':         0,
       'Attack':        4,
       'Bomber':        2,
       'CAS':           6,
       'Fighter':       5,
       'Fighter Multi': 4,
       'Strike Fighter':3}
ib_3000 = {'Attack':        0.25,
           'Bomber':        2}
ib_2000 = {'Attack':        0.35,
           'Bomber':        2,
           'Fighter Multi': 0.25,
           'Strike Fighter':0.5}
ib_1000 = {'Attack':        0.5,
           'Bomber':        1.5,
           'CAS':           0.25,
           'Fighter Multi': 0.75,
           'Strike Fighter':1.5}
ib_750  = {'Attack':        0.75,
           'Bomber':        1.5,
           'CAS':           0.9,
           'Fighter Multi': 1.2,
           'Strike Fighter':1.5}
ib_500  = {'Attack':        1,
           'Bomber':        1,
           'CAS':           3,
           'Fighter':       1,
           'Fighter Multi': 2,
           'Strike Fighter':3}
ib_250  = {'Attack':        1.5,
           'Bomber':        0.5,
           'CAS':           6,
           'Fighter':       1.5,
           'Fighter Multi': 1.75,
           'Strike Fighter':2}
ib_125  = {'Attack':        1,
           'CAS':           4,
           'Fighter':       2,
           'Fighter Multi': 1.5,
           'Strike Fighter':1}
gb_2000 = {'Attack':        0.5,
           'Bomber':        1,
           'Fighter Multi': 0.25,
           'Strike Fighter':0.5}
gb_1000 = {'Attack':        1.5,
           'Bomber':        1.5,
           'Fighter Multi': 1,
           'Strike Fighter':2}
gb_750  = {'Attack':        2,
           'Bomber':        1.5,
           'CAS':           0.5,
           'Fighter':       0.4,
           'Fighter Multi': 1.2,
           'Strike Fighter':2}
gb_500  = {'Attack':        2,
           'Bomber':        2,
           'CAS':           2,
           'Fighter':       1,
           'Fighter Multi': 2,
           'Strike Fighter':3}
gb_250  = {'Attack':        1.5,
           'Bomber':        0.5,
           'CAS':           4,
           'Fighter':       1.5,
           'Fighter Multi': 1.75,
           'Strike Fighter':2}
gb_125  = {'Attack':        1,
           'CAS':           6,
           'Fighter':       2,
           'Fighter Multi': 1.5,
           'Strike Fighter':1}
mine_bomb ={'ASuW':          0.13,
            'ASW':           0.13,
            'Attack':        0.19,
            'Bomber':        0.25,
            'Strike Fighter':0.19}
DC   ={'ASuW':          15,
       'ASW':           15,}
mine ={'ASuW':          1,
       'ASW':           1,
       'Attack':        0.5,
       'Bomber':        0.75,
       'Strike Fighter':0.5}
torpedo = {'ASuW':          5,
           'ASW':           5}
nuke_mis = {'Bomber':        0.08,
            'Fighter Multi': 0.04,
            'Strike Fighter':0.05}
ar_vlraam = {   'Fighter':       2.5,
                'Fighter Multi': 1.5}
ar_lraam  = {   'Fighter':       5,
                'Fighter Multi': 3,
                'Strike Fighter':2}
ar_mraam  = {   'Fighter':       7,
                'Fighter Multi': 4,
                'Strike Fighter':4}
ar_sraam  = {   'Fighter':       3.5,
                'Fighter Multi': 2}
sr_vlraam = {   'Fighter':       2,
                'Fighter Multi': 1.2}
sr_lraam  = {   'Fighter':       4,
                'Fighter Multi': 2.4,
                'Strike Fighter':1.6}
sr_mraam  = {   'Fighter':       5.6,
                'Fighter Multi': 3.2,
                'Strike Fighter':3.2}
sr_sraam  = {   'Fighter':       5.6,
                'Fighter Multi': 2.8,
                'Strike Fighter':1.6}
ir_sraam ={'Attack':        2,
           'Bomber':        1,
           'CAS':           1,
           'EW':            1,
           'Fighter':       3,
           'Fighter Multi': 1.5,
           'Strike Fighter':1}
ir_mraam ={'Attack':        2,
           'Bomber':        1,
           'CAS':           1,
           'EW':            1,
           'Fighter':       4,
           'Fighter Multi': 2.5,
           'Strike Fighter':2}
ir_lraam ={'Attack':        1,
           'Bomber':        0.5,
           'CAS':           0.5,
           'EW':            0.4,
           'Fighter':       5,
           'Fighter Multi': 3,
           'Strike Fighter':2}
ir_vlraam={'Fighter':       3,
           'Fighter Multi': 2,
           'Strike Fighter':0.5}
vsasm={'ASuW':          1,
       'ASW':           3,
       'Attack':        0.75,
       'Bomber':        0.5,
       'Fighter':       2,
       'Fighter Multi': 2.5,
       'Strike Fighter':1}
sasm ={'ASuW':          2.5,
       'ASW':           2,
       'Attack':        1.5,
       'Bomber':        2,
       'Fighter':       1.5,
       'Fighter Multi': 3,
       'Strike Fighter':1}
asm = {'ASuW':          3.5,
       'ASW':           1,
       'Attack':        1.5,
       'Bomber':        2,
       'Fighter':       1,
       'Fighter Multi': 3,
       'Strike Fighter':1}
lasm ={'ASuW':          2.75,
       'ASW':           0.75,
       'Attack':        1.1,
       'Bomber':        1.5,
       'Fighter':       0.5,
       'Fighter Multi': 2,
       'Strike Fighter':0.6}
vlasm={'ASuW':          2,
       'ASW':           0.5,
       'Attack':        0.75,
       'Bomber':        1,
       'Fighter':       0.25,
       'Fighter Multi': 0.75,
       'Strike Fighter':0.25}
usagm={'ASuW':          2,
       'ASW':           2,
       'Attack':        5,
       'CAS':           3,
       'Fighter Multi': 2,
       'Strike Fighter':2}
vsagm={'ASuW':          0.25,
       'ASW':           0.75,
       'Attack':        1.5,
       'Bomber':        1,
       'CAS':           1.5,
       'Fighter':       2,
       'Fighter Multi': 2.5,
       'Strike Fighter':1}
sagm ={'ASuW':          0.6,
       'ASW':           0.5,
       'Attack':        3,
       'Bomber':        4,
       'CAS':           2,
       'Fighter':       1.5,
       'Fighter Multi': 3,
       'Strike Fighter':1}
agm = {'ASuW':          0.9,
       'ASW':           0.25,
       'Attack':        3,
       'Bomber':        4,
       'CAS':           1,
       'Fighter':       1,
       'Fighter Multi': 3,
       'Strike Fighter':1}
lagm ={'ASuW':          0.7,
       'ASW':           0.2,
       'Attack':        2.25,
       'Bomber':        3,
       'CAS':           0.5,
       'Fighter':       0.5,
       'Fighter Multi': 2,
       'Strike Fighter':0.6}
vlagm={'ASuW':          0.5,
       'ASW':           0.1,
       'Attack':        1.5,
       'Bomber':        2,
       'CAS':           0,
       'Fighter':       0.25,
       'Fighter Multi': 0.75,
       'Strike Fighter':0.25}
usagsm={'ASuW':          2,
       'ASW':           2,
       'Attack':        5,
       'CAS':           3,
       'Fighter Multi': 2,
       'Strike Fighter':2}
vsagsm={'ASuW':          2,
       'ASW':           2,
       'Attack':        2.2,
       'CAS':           3,
       'Fighter':       1,
       'Fighter Multi': 2,
       'Strike Fighter':0.5}
sagsm ={'ASuW':          1.6,
       'ASW':           1.25,
       'Attack':        2.25,
       'Bomber':        3,
       'CAS':           1,
       'Fighter':       1.5,
       'Fighter Multi': 3,
       'Strike Fighter':1}
agsm = {'ASuW':          2.2,
       'ASW':           0.6,
       'Attack':        2.25,
       'Bomber':        3,
       'CAS':           0.5,
       'Fighter':       1,
       'Fighter Multi': 3,
       'Strike Fighter':1}
lagsm ={'ASuW':          1.7,
       'ASW':           0.47,
       'Attack':        1.68,
       'Bomber':        2.25,
       'CAS':           0.25,
       'Fighter':       0.5,
       'Fighter Multi': 2,
       'Strike Fighter':0.6}
vlagsm={'ASuW':          1.25,
       'ASW':           0.3,
       'Attack':        1.13,
       'Bomber':        1.5,
       'Fighter':       0.25,
       'Fighter Multi': 0.75,
       'Strike Fighter':0.25}
vsarm={'Attack':        1,
       'Bomber':        0,
       'CAS':           1,
       'EW':            3,
       'Fighter'      : 0.25,
       'Fighter Multi': 0.38,
       'Strike Fighter':0.5}
sarm ={'Attack':        2,
       'Bomber':        0,
       'CAS':           2,
       'EW':            6,
       'Fighter'      : 0.5,
       'Fighter Multi': 0.75,
       'Strike Fighter':1}
arm = {'Attack':        3,
       'Bomber':        0.5,
       'CAS':           1,
       'EW':            6,
       'Fighter'      : 1,
       'Fighter Multi': 1.5,
       'Strike Fighter':2}
larm ={'Attack':        1,
       'Bomber':        1,
       'CAS':           0,
       'EW':            4,
       'Fighter'      : 0.5,
       'Fighter Multi': 1,
       'Strike Fighter':1.5}
vlarm={'Attack':        0,
       'Bomber':        2,
       'CAS':           0,
       'EW':            2,
       'Fighter'      : 0,
       'Fighter Multi': 0.5,
       'Strike Fighter':1}