#aircraft * sorties * weapon_count = stock to carry
role_ratios = {
    'Sorties':                        {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':3,  'ASW':5,  'Attack':3,  'Bomber':1.5,'CAS':4,  'EW':2,  'Fighter':4,  'Fighter Multi':3,  'Strike Fighter':3},
    'GP HC 8000':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'FAB-3000':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'GP MC 4000':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'FAB-1500':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'M118':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'FAB-1000':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'Mk-84':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.5, 'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'GP MC 1900':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.5, 'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'FAB-500':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.5, 'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'GB-500':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.75,'Bomber':2,  'CAS':1.3,'EW':0,  'Fighter':.5, 'Fighter Multi':1.5,'Strike Fighter':1.8},
    'GP MC 1000':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.75,'Bomber':2,  'CAS':1.3,'EW':0,  'Fighter':.5, 'Fighter Multi':1.5,'Strike Fighter':1.8},
    'Mk-83':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.75,'Bomber':2,  'CAS':1.3,'EW':0,  'Fighter':.5, 'Fighter Multi':1.5,'Strike Fighter':1.8},
    'M117':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.5,'Strike Fighter':1.5},
    'FAB-250':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.5,'Strike Fighter':1.5},
    'Mk-82':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.8,'Strike Fighter':2},
    'GP MC 500':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.8,'Strike Fighter':2},
    'GB-200':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.8,'Strike Fighter':2},
    'Durandal':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':2,  'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':1.8,'Strike Fighter':2},
    'Mk-81':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1.5,'Bomber':1.5,'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.5,'Strike Fighter':1.5},
    'GP MC 250':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1.5,'Bomber':1.5,'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.5,'Strike Fighter':1.5},
    'FAB-100':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1.5,'Bomber':1.5,'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.5,'Strike Fighter':1.5},
    'AP 1500':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.5, 'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'BLU-1/B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.5, 'Bomber':1.5,'CAS':1,  'EW':0,  'Fighter':0,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-130':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':0.5,'Attack':1.5,'Bomber':.5, 'CAS':1.5,'EW':0,  'Fighter':.75,'Fighter Multi':.85,'Strike Fighter':1},
    'GBU-28B/B':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-11/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'KAB-1500Kr':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'KAB-1500L':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'KAB-500R':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-10/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-24/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-24B/B':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-27':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':1,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':1},
    'GBU-31A(v)2':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'GBU-31B(v)2':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'GBU-31C(v)4':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'SPICE-1000':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'KAB-500KRU':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'KAB-500L':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.5, 'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.5, 'Strike Fighter':.5},
    'GBU-32A(v)2':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':0,  'Attack':1,  'Bomber':1,  'CAS':.5, 'EW':0,  'Fighter':0,  'Fighter Multi':.75,'Strike Fighter':1},
    'GBU-32B(v)2':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':0,  'Attack':1,  'Bomber':1,  'CAS':.5, 'EW':0,  'Fighter':0,  'Fighter Multi':.75,'Strike Fighter':1},
    'GBU-32C(v)4':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':0,  'Attack':1,  'Bomber':1,  'CAS':.5, 'EW':0,  'Fighter':0,  'Fighter Multi':.75,'Strike Fighter':1},
    'KAB-500Kr':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':0,  'Attack':1,  'Bomber':1,  'CAS':.5, 'EW':0,  'Fighter':0,  'Fighter Multi':.75,'Strike Fighter':1},
    'GBU-15/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2.5,'ASW':0,  'Attack':2.5,'Bomber':2,  'CAS':1,  'EW':0,  'Fighter':.5, 'Fighter Multi':1.2,'Strike Fighter':1.5},
    'GBU-16/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2.5,'ASW':0,  'Attack':2.5,'Bomber':2,  'CAS':1,  'EW':0,  'Fighter':.5, 'Fighter Multi':1.2,'Strike Fighter':1.5},
    'GBU-1/B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2.5,'ASW':0,  'Attack':2.5,'Bomber':2,  'CAS':1,  'EW':0,  'Fighter':.5, 'Fighter Multi':1.2,'Strike Fighter':1.5},
    'GBU-12/B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':1,  'EW':0,  'Fighter':1,  'Fighter Multi':1.5,'Strike Fighter':1.5},
    'GBU-30':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':4,  'ASW':0,  'Attack':2,  'Bomber':1.5,'CAS':1.5,'EW':0,  'Fighter':.5, 'Fighter Multi':1.2,'Strike Fighter':1.5},
    'GBU-39 SDB':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':1,  'EW':0,  'Fighter':1,  'Fighter Multi':1.4,'Strike Fighter':1.5},
    'AGM-84A Harpoon':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84C Harpoon':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84D Harpoon':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84F Harpoon':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84G Harpoon':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84E SLAM':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AGM-84H SLAM-ER':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    '3M80 Moskit':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AM-39 Exocet':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AS.34 Kormoran':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AS.34 Kormoran II':              {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'AS.37 Martel':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'ASM-1':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'BAe Sea Eagle':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'Gabriel Mk3A/S':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'Kh-35U':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'Kh-59MK':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'NSM':                            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'SCALP EG':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'SCALP Naval':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'Storm Shadow':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'X-29TE':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'X-31A':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'YJ-82K':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'YJ-83K':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'YJ-85K':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3.5,'ASW':1,  'Attack':3,  'Bomber':4,  'CAS':0,  'EW':0,  'Fighter':.75,'Fighter Multi':1,  'Strike Fighter':.9},
    'K-10S':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'KSR-2':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'KSR-5':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'KD-63':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'KS-1 Kometa':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'Kh-15A':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'Kh-22':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'Kh-22M':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'Kh-15SE':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'YJ-1':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'YJ-6':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'YJ-61':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'YJ-62K':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2  ,'ASW':0.5,'Attack':1.5,'Bomber':2,  'CAS':0,  'EW':0,  'Fighter':.37,'Fighter Multi':0.5,'Strike Fighter':.45},
    'BGM-71A Tow':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    'BGM-71E Tow 2':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    'AGM-114 Hellfire':               {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    '9M113 Konkurs':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    '9M14 Malyutka':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    '9M17MP Skorpion-P':              {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    'Brimstone':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':5,  'Bomber':0,  'CAS':3,  'EW':0,  'Fighter':0,  'Fighter Multi':2,  'Strike Fighter':2},
    'AGM-119A':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'AGM-119B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'AGM-119C':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'Penguin Mk2':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'AS 12':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'Marte':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'Marte Mk2':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'Marte Mk2/S':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'Sea Skua':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':2,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':1,  'Strike Fighter':0},
    'AGM-12A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':3,  'Bomber':1,  'CAS':3,  'EW':0,  'Fighter':1.5,'Fighter Multi':1.7,'Strike Fighter':2},
    'AGM-12B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':3,  'Bomber':1,  'CAS':3,  'EW':0,  'Fighter':1.5,'Fighter Multi':1.7,'Strike Fighter':2},
    'AGM-12C':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':3,  'Bomber':1,  'CAS':3,  'EW':0,  'Fighter':1.5,'Fighter Multi':1.7,'Strike Fighter':2},
    'AGM-158A JASSM':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':1,  'Bomber':1.5,'CAS':0,  'EW':0,  'Fighter':0.5,'Fighter Multi':.67,'Strike Fighter':1},
    'AS-15TT':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':3,  'Bomber':1,  'CAS':3,  'EW':0,  'Fighter':1.5,'Fighter Multi':1.7,'Strike Fighter':2},
    'Kh-66':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':3,  'Bomber':1,  'CAS':3,  'EW':0,  'Fighter':1.5,'Fighter Multi':1.7,'Strike Fighter':2},
    'TL-10':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'YJ-7':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-45A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':4,  'Bomber':0,  'CAS':.5, 'EW':7,  'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'AGM-45B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':4,  'Bomber':0,  'CAS':.5, 'EW':7,  'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'Kh-25MP':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':4,  'Bomber':0,  'CAS':.5, 'EW':7,  'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'AGM-88A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'AGM-88B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'AGM-88C':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'ALARM':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'Kh-15P':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'Kh-22MP':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'Kh-31P':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'X-31P':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':3,  'Bomber':2,  'CAS':1,  'EW':6,  'Fighter':1,  'Fighter Multi':2,  'Strike Fighter':2},
    'AGM-78A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':2, 'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'AGM-78B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':2, 'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'AGM-78C':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':2, 'Fighter':.5, 'Fighter Multi':1,  'Strike Fighter':1},
    'AGM-78D':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':2, 'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Kh-58':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':2, 'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'AGM-62':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-62 mk3':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-62 mk5':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-62 mk21':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-62 mk23':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':2,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.3,'Strike Fighter':1.5},
    'AGM-65A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.7,'Strike Fighter':2},
    'AGM-65B':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65D':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65E':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65F':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65G':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65J':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AGM-65K':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AS-30':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AS-30L':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-23':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-25ML':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-29L':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-29T':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-59':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'Kh-59M':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'TL-6':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':2,  'Bomber':1,  'CAS':2,  'EW':0,  'Fighter':1,  'Fighter Multi':1.2,'Strike Fighter':2},
    'AAM-N-7 Sidewinder':             {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9B':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9C':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9D':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9E':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9G':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9H':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9J':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9L':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9M':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9N':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9P':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9P4':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-9X':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AIM-132 ASRAAM':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AAM-1':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AAM-3':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AAM-5':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'IRIS-T':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'MAA-1A':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-5B':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-5C':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-5E':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-7':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-7B':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-8':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-8A':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'PL-8B':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'Python 3':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'Python 4':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'Python 5':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-60':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-60M':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-60MK':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-73':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-73E':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-73M':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R-73M2':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R.550 Magic':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'R.550 Magic II':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':2.5,'Strike Fighter':2},
    'AAM-N-6 Sparrow':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7C':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7D':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7E':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7F':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7M':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'AIM-7P':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'MICA IR':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'MICA RF':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'Derby':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'ASPIDE-1A':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'Aspide 2000':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'PL-11':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':6,  'Fighter Multi':3,  'Strike Fighter':3},
    'PL-11A':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120A':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120B':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120C':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120C5':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120C7':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-120D':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'PL-11 AMR':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'MBDA Meteor':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AAM-4':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AAM-4b':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'PL-12':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-27R':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-27T':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-40R':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-40T':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-4R':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-4RM':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-4T':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-4TM':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-77':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-77T':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'R-77PL':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'Skyflash':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'Super 530D':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'Super 530F':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':7,  'Fighter Multi':4,  'Strike Fighter':4},
    'AIM-54A':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'AIM-54C':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'AIM-54C ECCM':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'PL-13':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-23R':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-23T':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-24R':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-24T':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-27RE':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-27TE':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R-33':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'R.530':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':2.5,'Fighter Multi':1.5,'Strike Fighter':0},
    'AIM-4':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4A':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4C':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4D':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4E':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4F':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'AIM-4G':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'FireStreak':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'Red Top':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'K-5M':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'PL-2A':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'PL-2B':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'R-3M':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'R-3R':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'R-3S':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'Shafrir 1':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'Shafrir 2':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':2,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    'Hydra-70 Rocket':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'Mk-40 FFAR':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    '50mm (2in) FFAR Rockets':        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'Zuni 127mm':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    '5in FFAR':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    '5in HVAR':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    '68mm SNEB Rockets':              {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-24B 240mm':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-25C 266mm':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-25OF 266mm':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-3K 160mm':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-5K 57mm':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-5K Rocket':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-5M Rocket':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-8B 80mm':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'S-8K 80mm':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'RP-3 AP':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'RP-3 HE':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'Mk 71 Zuni WAFAR':               {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'Mk 16 Zuni FFAR':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':2,  'ASW':2,  'Attack':7,  'Bomber':3,  'CAS':5,  'EW':0,  'Fighter':0,  'Fighter Multi':4,  'Strike Fighter':5},
    'Kh-15':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'Kh-22N':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'Kh-58U':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'AGM-69A 15kT':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'AGM-69A 70kT':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'AGM-69A 140kT':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'AGM-69A 210kT':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':0,  'Bomber':.08,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':.04,'Strike Fighter':.05},
    'B-41 25MT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-53 9MT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-53 5MT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-39 3.5MT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-53 2.5MT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-28 Mod5 1.45MT':               {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 1200kT':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-28 Mod1 1.1MT':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-53 1MT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-43 1MT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 800kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-43 700kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 400kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-28 Mod2 350kT':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 340kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-43 300kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 200kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 170kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 100kT':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 80kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-43 70kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-28 Mod3 70kT':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 60kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 50kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-83 25kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-57 Mod5 20kT':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-57 Mod3 15kT':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 10kT':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-57 Mod1 10kT':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 5kT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-57 Mod0 5kT':                  {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'B-61 1kT':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'RDS 220 Tsar Bomba':             {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'RN-25':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'RN-28':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'Red Beard 20kT':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'TN-1000':                        {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':0,  'ASW':0,  'Attack':.17,'Bomber':.17,'CAS':0,  'EW':0,  'Fighter':.17,'Fighter Multi':.17,'Strike Fighter':.17},
    'Mk-44':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-46 LWT Mod2':                 {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-46 Mod5':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-50':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-54':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'A-244S':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'A-244S Mod1':                    {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'APR-2E':                         {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'AT-1':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'AT-2M':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-T1':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'MU-90':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Stingray':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'VTT-1':                          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Yu-7':                           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':5,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-10 DC':                       {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':15, 'ASW':15, 'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    'Mk-36 DST':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':.13,'ASW':.13,'Attack':.19,'Bomber':.25,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.19},
    'Mk-40 DST':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':.13,'ASW':.13,'Attack':.19,'Bomber':.25,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.19},
    'Mk-41 DST':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':.13,'ASW':.13,'Attack':.19,'Bomber':.25,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.19},
    'Mk-59 DST':                      {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':.13,'ASW':.13,'Attack':.19,'Bomber':.25,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.19},
    'Mk-56 Mine':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-57 Mine':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-60 CAPTOR':                   {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-10 Mod5 Mine':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-10 Mod6 Mine':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-25 Mine':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-36 Mod1 Mine':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-36 Mod2 Mine':                {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    'Mk-39 Mine':                     {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':1,  'ASW':1,  'Attack':.5, 'Bomber':.75,'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':.5},
    "310 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "100 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "400 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "PTB-400":                        {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "120 gallon tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "150 gallon tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "300 gallon tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "450 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "PTB-490":                        {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "500 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "PTB-600":                        {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "600 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Tanque de 600 litros":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "625 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "700 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "190 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "750 litre tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "750 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "782 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "800 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "PTB-800":                        {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "900 liter tank":                 {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1000 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "FPU-1":                          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "285 Gallon Internal Tank FB-111":{'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1100 Liter Tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "300 Gallon Internal Tank FB-111":{'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "300 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Tanque de 300 galones":          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1150 Liter Tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "PTB 1150":                       {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "FPU-6":                          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1200 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "330 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Tanque de 330 galones":          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1250 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "FPU-8":                          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "370 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Tanque de 370 galones":          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1400 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1520 Liter Tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "1700 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "2000 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Lightning Ventral Tank":         {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "594 gallon wing tank":           {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "600 gallon centerline tank":     {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "Tanque de 600 galones":          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "600 gallon tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "FPU-7":                          {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "3000 liter tank":                {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "AJ500 Fuel":                     {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "AJ840 Fuel":                     {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    "AJ1340 Fuel":                    {'Tanker':2,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':1,  'Bomber':1,  'CAS':1,  'EW':1,  'Fighter':1,  'Fighter Multi':1,  'Strike Fighter':1},
    ".50 cal bullet air":             {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    ".50 cal bullet air(x2)":         {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    ".50 cal bullet":                 {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "12.7mm YaKB Burst":              {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20mm HS.404 x2":                 {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20mm HS.404":                    {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20mm M53 API":                   {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20mm PGU":                       {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20mm PGU-28/B":                  {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20x102 mm burst":                {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20x110 mm x2":                   {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "20x110 mm":                      {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "23mm AM-23":                     {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "23mm AM/NR-23 HEI x2":           {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "23mm AM/NR-23 HEI":              {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "23mm GSh-23 HEI":                {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "27mm DM10 FAPDS":                {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "27mm HE":                        {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm ADEN API":                  {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm DEFA":                      {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm M230 Chaingun Ammo":        {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm NR-30 HEI x2":              {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm NR-30 HEI":                 {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm OP-84 FRAG Tracer AK-306":  {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm PGU-14/B API":              {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30mm Su-25":                     {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "30x150mm GIAT":                  {'Tanker':1,  'Recon':1,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':6,  'EW':1,  'Fighter':5,  'Fighter Multi':4,  'Strike Fighter':3},
    "Chaff-1":                        {'Tanker':2,  'Recon':2,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':4,  'EW':2,  'Fighter':5,  'Fighter Multi':5,  'Strike Fighter':4},
    "Flare-1":                        {'Tanker':2,  'Recon':2,  'AEW':1,  'ASuW':1,  'ASW':1,  'Attack':4,  'Bomber':2,  'CAS':4,  'EW':2,  'Fighter':5,  'Fighter Multi':5,  'Strike Fighter':4},
    "DICASS (50) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (55) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (60) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (65) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (70) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (75) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (80) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (85) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (90) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (95) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (100) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (105) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (110) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (115) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (120) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DICASS (125) Sonobuoy":          {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (50) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (55) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (60) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (65) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (70) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (75) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (80) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (85) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (90) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (95) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (100) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (105) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (110) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (115) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (120) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "DIFAR (125) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (50) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (55) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (60) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (65) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (70) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (75) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (80) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (85) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (90) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (95) Sonobuoy":            {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (100) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (105) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (110) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (115) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (120) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    "LOFAR (125) Sonobuoy":           {'Tanker':0,  'Recon':0,  'AEW':0,  'ASuW':3,  'ASW':5,  'Attack':0,  'Bomber':0,  'CAS':0,  'EW':0,  'Fighter':0,  'Fighter Multi':0,  'Strike Fighter':0},
    }

