Alliance_List = {
    #'Nato': {
    'NATO 24/8/1949':{ 'Start':1949.644, 'Stop':1952.131, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada']},
    'NATO 18/2/1952':{ 'Start':1952.131, 'Stop':1955.351, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey']},
    'NATO 9/5/1955':{ 'Start':1955.351, 'Stop':1966.186, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'NATO 10/3/1966':{ 'Start':1966.186, 'Stop':1974.616, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'NATO 14/8/1974':{ 'Start':1974.616, 'Stop':1980.801, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Turkey', 'Germany, Federal Republic']},
    'NATO 20/10/1980':{ 'Start':1980.801, 'Stop':1982.408, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'NATO 30/5/1982':{ 'Start':1982.408, 'Stop':1990.753, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic', 'Spain']},
    'NATO 3/10/1990':{ 'Start':1990.753, 'Stop':1999.192, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain']},
    'NATO 12/3/1999':{ 'Start':1999.192, 'Stop':2004.240, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland']},
    'NATO 29/3/2004':{'Start':2004.240, 'Stop':2009.247, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania', 'Romania', 'Slovakia', 'Slovenia']},
    'NATO 1/4/2009':{'Start':2009.247, 'Stop':2999.000, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania', 'Romania', 'Slovakia', 'Slovenia', 'Albania', 'Croatia']},
    'nato 1949/8':{ 'Start':1949.644, 'Stop':1952.131, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada']},
    'nato 1952/2':{ 'Start':1952.131, 'Stop':1955.351, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey']},
    'nato 1955/5':{ 'Start':1955.351, 'Stop':1966.186, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'nato 1966/3':{ 'Start':1966.186, 'Stop':1974.616, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'nato 1974/8':{ 'Start':1974.616, 'Stop':1980.801, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Turkey', 'Germany, Federal Republic']},
    'nato 1980/10':{ 'Start':1980.801, 'Stop':1982.408, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic']},
    'nato 1982/5':{ 'Start':1982.408, 'Stop':1990.753, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany, Federal Republic', 'Spain']},
    'nato 1990/10':{ 'Start':1990.753, 'Stop':1999.192, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain']},
    'nato 1999/3':{ 'Start':1999.192, 'Stop':2004.240, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland']},
    'nato 2004/3':{'Start':2004.240, 'Stop':2009.247, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania', 'Romania', 'Slovakia', 'Slovenia']},
    'nato 2009/4':{'Start':2009.247, 'Stop':2999.000, 'Members':['US', 'UK', 'France', 'Belgium', 'Netherlands', 'Luxembourg', 'Italy', 'Portugal', 'Denmark', 'Norway', 'Canada', 'Greece', 'Turkey', 'Germany', 'Spain', 'Czech Republic', 'Hungary', 'Poland', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania', 'Romania', 'Slovakia', 'Slovenia', 'Albania', 'Croatia']},
    #       },
    #'Warsaw Pact': {
    'Warsaw Pact 14/5/1955':{'Start':1955.364, 'Stop':1968.699, 'Members':['Albania','Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Romania','Russia']},
    'Warsaw Pact 13/9/1968':{'Start':1968.699, 'Stop':1989.986, 'Members':['Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Romania','Russia']},
    'Warsaw Pact 27/12/1989':{'Start':1989.986, 'Stop':1990.307, 'Members':['Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Russia']},
    'Warsaw Pact 23/4/1990':{'Start':1990.307, 'Stop':1990.729, 'Members':['Bulgaria','Germany, Democratic Republic','Hungary','Poland','Russia']},
    'Warsaw Pact 24/9/1990':{'Start':1990.729, 'Stop':1990.871, 'Members':['Bulgaria','Hungary','Poland','Russia']},
    'Warsaw Pact 15/11/1990':{'Start':1990.871, 'Stop':1991.151, 'Members':['Hungary','Poland','Russia']},
    'wpac 1955/5':{'Start':1955.364, 'Stop':1968.699, 'Members':['Albania','Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Romania','Russia']},
    'wpac 1968/9':{'Start':1968.699, 'Stop':1989.986, 'Members':['Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Romania','Russia']},
    'wpac 1989/12':{'Start':1989.986, 'Stop':1990.307, 'Members':['Bulgaria','Czechoslovakia','Germany, Democratic Republic','Hungary','Poland','Russia']},
    'wpac 1990/4':{'Start':1990.307, 'Stop':1990.729, 'Members':['Bulgaria','Germany, Democratic Republic','Hungary','Poland','Russia']},
    'wpac 1990/9':{'Start':1990.729, 'Stop':1990.871, 'Members':['Bulgaria','Hungary','Poland','Russia']},
    'wpac 1990/11':{'Start':1990.871, 'Stop':1991.151, 'Members':['Hungary','Poland','Russia']},
    #        }
    }
Country_Aliases = {
    'USSR':'Russia',
    'Russian Federation':'Russia',
    }
    